### ISSUE TITLE
Bob's Ultimate To-Do List

### ISSUE THREAD

**Issue by bobgeorgethe3rd** [bobgeorgethe3rd/freesewing#4]
Docs/Markdown

- [ ] Get Carlton and Carlita's curretn stuff ready to merge without instructions
- [ ] Carlton and Carlita's missing Collar Option info
- [ ] Diagrams for Holmes, will need to make a Holmes for this.
- [ ] Hortensia's Pattern Options
- [ ] Waralee Doc update, Shipping without pockets and a fixme instead.

Development

- [ ] Tidy up desk/room and find safe place for Minerva
- [ ] Find Small Scissors (have replacement if can't)
- [ ] Setup new Printer
- [ ] Buy fabric for Billy Bucket Hat
- [ ] Pre-wash Billy fabric.
- [ ] Test Billy Pucket Hat
- [ ] Ship Billy if not alterations are needed.
- [ ] Finish Skirt of Scott
- [ ] Separate out Scott's Skirt to produce Harriet with waist to hip ec like Sandy/Penelope
- [ ] Put Harriet out for Testing
- [ ] Test new Laura whilst Harriet is being tested, see if Shark would like to test too.
- [ ] Put Laura back out to testing if it goes well.
- [ ] Make changes to Harriet if required/requested and get ready to Ship
- [ ] Start next dress
- [ ] Bee conditional options when added
- [ ] Add conditional opitons to those in develop that need it when added.
- [ ] Hopefully by the time dress 7 comes along the new development is available
- [ ] When the new development is available place all the skirts into it and maybe the Bella Update as well.
- [ ] Simon(e) Buttonhole config once new develop is out.

Self

- [ ] Finish Minerva
- [ ] Make Navy and Magenta hooded Tee
- [ ] Organise Stash and Self - Projects.
